"""add category description, unify timestamps on base

Revision ID: 4ec165b8aa08
Revises: d6cb8ae88fd6
Create Date: 2026-07-31 22:14:59.989089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ec165b8aa08'
down_revision: Union[str, Sequence[str], None] = 'd6cb8ae88fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_chat', sa.Column('create_at', sa.DateTime(), nullable=False, comment='Creation time'))
    op.add_column('ai_chat', sa.Column('update_at', sa.DateTime(), nullable=False, comment='Update time'))
    op.drop_column('ai_chat', 'created_at')
    op.add_column('favorite', sa.Column('create_at', sa.DateTime(), nullable=False, comment='Creation time'))
    op.add_column('favorite', sa.Column('update_at', sa.DateTime(), nullable=False, comment='Update time'))
    op.drop_column('favorite', 'created_at')
    op.add_column('history', sa.Column('create_at', sa.DateTime(), nullable=False, comment='Creation time'))
    op.add_column('history', sa.Column('update_at', sa.DateTime(), nullable=False, comment='Update time'))
    op.add_column('news', sa.Column('create_at', sa.DateTime(), nullable=False, comment='Creation time'))
    op.add_column('news', sa.Column('update_at', sa.DateTime(), nullable=False, comment='Update time'))
    op.drop_column('news', 'created_at')
    op.add_column('news_category', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('news_category', sa.Column('create_at', sa.DateTime(), nullable=False, comment='Creation time'))
    op.add_column('news_category', sa.Column('update_at', sa.DateTime(), nullable=False, comment='Update time'))
    op.add_column('related_news', sa.Column('create_at', sa.DateTime(), nullable=False, comment='Creation time'))
    op.add_column('related_news', sa.Column('update_at', sa.DateTime(), nullable=False, comment='Update time'))
    op.add_column('user_token', sa.Column('create_at', sa.DateTime(), nullable=False, comment='Creation time'))
    op.add_column('user_token', sa.Column('update_at', sa.DateTime(), nullable=False, comment='Update time'))
    op.drop_column('user_token', 'created_at')
    op.add_column('users', sa.Column('create_at', sa.DateTime(), nullable=False, comment='Creation time'))
    op.add_column('users', sa.Column('update_at', sa.DateTime(), nullable=False, comment='Update time'))
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('users', 'update_at')
    op.drop_column('users', 'create_at')
    op.add_column('user_token', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('user_token', 'update_at')
    op.drop_column('user_token', 'create_at')
    op.drop_column('related_news', 'update_at')
    op.drop_column('related_news', 'create_at')
    op.drop_column('news_category', 'update_at')
    op.drop_column('news_category', 'create_at')
    op.drop_column('news_category', 'description')
    op.add_column('news', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('news', 'update_at')
    op.drop_column('news', 'create_at')
    op.drop_column('history', 'update_at')
    op.drop_column('history', 'create_at')
    op.add_column('favorite', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('favorite', 'update_at')
    op.drop_column('favorite', 'create_at')
    op.add_column('ai_chat', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('ai_chat', 'update_at')
    op.drop_column('ai_chat', 'create_at')
    # ### end Alembic commands ###
