"""drop related_news table

Revision ID: 677d3acff97f
Revises: fc1ed9bb6fad
Create Date: 2026-08-01 13:23:44.922580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '677d3acff97f'
down_revision: Union[str, Sequence[str], None] = 'fc1ed9bb6fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_news')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_news',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('related_news_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Creation time'),
    sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Update time'),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('related_news_news_id_fkey')),
    sa.ForeignKeyConstraint(['related_news_id'], ['news.id'], name=op.f('related_news_related_news_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('related_news_pkey')),
    sa.UniqueConstraint('news_id', 'related_news_id', name=op.f('uq_related_news_pair'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
