"""restructure news table: add description, image, author, views, publish_time, indexes

Revision ID: aeada030b7f0
Revises: f110d9febcd1
Create Date: 2026-07-31 23:26:29.193910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeada030b7f0'
down_revision: Union[str, Sequence[str], None] = 'f110d9febcd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('description', sa.String(length=500), nullable=True, comment='News summary'))
    op.add_column('news', sa.Column('image', sa.String(length=255), nullable=True, comment='Cover image URL'))
    op.add_column('news', sa.Column('author', sa.String(length=50), nullable=True, comment='Author'))
    op.add_column('news', sa.Column('views', sa.Integer(), nullable=False, comment='View count'))
    op.add_column('news', sa.Column('publish_time', sa.DateTime(), nullable=False, comment='Publish time'))
    op.alter_column('news', 'id',
               existing_type=sa.INTEGER(),
               comment='News ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('news', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='News title',
               existing_nullable=False)
    op.alter_column('news', 'content',
               existing_type=sa.TEXT(),
               comment='News content',
               existing_nullable=False)
    op.alter_column('news', 'category_id',
               existing_type=sa.INTEGER(),
               comment='Category ID',
               existing_nullable=False)
    op.create_index('fk_news_category_idx', 'news', ['category_id'], unique=False)
    op.create_index('idx_publish_time', 'news', ['publish_time'], unique=False)
    op.drop_constraint(op.f('news_author_id_fkey'), 'news', type_='foreignkey')
    op.drop_column('news', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('news_author_id_fkey'), 'news', 'users', ['author_id'], ['id'])
    op.drop_index('idx_publish_time', table_name='news')
    op.drop_index('fk_news_category_idx', table_name='news')
    op.alter_column('news', 'category_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Category ID',
               existing_nullable=False)
    op.alter_column('news', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='News content',
               existing_nullable=False)
    op.alter_column('news', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='News title',
               existing_nullable=False)
    op.alter_column('news', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='News ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('news', 'publish_time')
    op.drop_column('news', 'views')
    op.drop_column('news', 'author')
    op.drop_column('news', 'image')
    op.drop_column('news', 'description')
    # ### end Alembic commands ###
