"""add user profile fields and multi-device token support

Revision ID: bb1faf1b798d
Revises: e1adea5de55e
Create Date: 2026-08-01 13:42:30.752088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb1faf1b798d'
down_revision: Union[str, Sequence[str], None] = 'e1adea5de55e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_token', sa.Column('token_id', sa.String(length=64), nullable=False, comment='Token identifier (uuid)'))
    op.add_column('user_token', sa.Column('is_revoked', sa.Boolean(), nullable=False, comment='Whether the token was revoked'))
    op.alter_column('user_token', 'id',
               existing_type=sa.INTEGER(),
               comment='Row ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_token', 'user_id',
               existing_type=sa.INTEGER(),
               comment='Owner user ID',
               existing_nullable=False)
    op.alter_column('user_token', 'access_token',
               existing_type=sa.VARCHAR(length=500),
               comment='Access token',
               existing_nullable=False)
    op.alter_column('user_token', 'refresh_token',
               existing_type=sa.VARCHAR(length=500),
               comment='Refresh token',
               existing_nullable=True)
    op.alter_column('user_token', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Expiry time',
               existing_nullable=False)
    op.drop_constraint(op.f('user_token_user_id_key'), 'user_token', type_='unique')
    op.create_index(op.f('ix_user_token_token_id'), 'user_token', ['token_id'], unique=True)
    op.create_index(op.f('ix_user_token_user_id'), 'user_token', ['user_id'], unique=False)
    op.add_column('users', sa.Column('nickname', sa.String(length=50), nullable=True, comment='Display name'))
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True, comment='Gender: male / female / other'))
    op.add_column('users', sa.Column('status', sa.String(length=20), nullable=False, comment='Account status'))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='Last login time'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'status')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'nickname')
    op.drop_index(op.f('ix_user_token_user_id'), table_name='user_token')
    op.drop_index(op.f('ix_user_token_token_id'), table_name='user_token')
    op.create_unique_constraint(op.f('user_token_user_id_key'), 'user_token', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_token', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Expiry time',
               existing_nullable=False)
    op.alter_column('user_token', 'refresh_token',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Refresh token',
               existing_nullable=True)
    op.alter_column('user_token', 'access_token',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Access token',
               existing_nullable=False)
    op.alter_column('user_token', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Owner user ID',
               existing_nullable=False)
    op.alter_column('user_token', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Row ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('user_token', 'is_revoked')
    op.drop_column('user_token', 'token_id')
    # ### end Alembic commands ###
