"""add bio and avatar to users, make email nullable

Revision ID: e1adea5de55e
Revises: 677d3acff97f
Create Date: 2026-08-01 13:36:39.940826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1adea5de55e'
down_revision: Union[str, Sequence[str], None] = '677d3acff97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True, comment='User bio'))
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True, comment='Avatar URL'))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='User ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='Username',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment='Email')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='Hashed password',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Hashed password',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='Email')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Username',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='User ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
