"""replace category description with sort_order

Revision ID: f110d9febcd1
Revises: 4ec165b8aa08
Create Date: 2026-07-31 22:37:37.436826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f110d9febcd1'
down_revision: Union[str, Sequence[str], None] = '4ec165b8aa08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_category', sa.Column('sort_order', sa.Integer(), nullable=False, comment='Sort order'))
    op.alter_column('news_category', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='Category name',
               existing_nullable=False)
    op.drop_column('news_category', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_category', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('news_category', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Category name',
               existing_nullable=False)
    op.drop_column('news_category', 'sort_order')
    # ### end Alembic commands ###
