"""add author_id fk back to news

Revision ID: fc1ed9bb6fad
Revises: aeada030b7f0
Create Date: 2026-07-31 23:29:13.252909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1ed9bb6fad'
down_revision: Union[str, Sequence[str], None] = 'aeada030b7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('author_id', sa.Integer(), nullable=True, comment='Author user ID'))
    op.create_foreign_key(None, 'news', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'author_id')
    # ### end Alembic commands ###
